name: papercups_flutter
description: Native Flutter implementation of the papercups.io chat widget.
version: 3.1.2
homepage: https://github.com/aguilaair/papercups_flutter

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: ">=0.5.3 <0.7.0"
  http: ^1.1.0
  universal_io: ^2.0.4
  flutter_markdown: ">=0.5.2 <0.7.0"
  timeago: ">=2.0.30 <4.0.0"
  intl: ^0.19.0
  file_picker: ^5.2.5
  path_provider: ^2.0.1
  url_launcher: ^6.1.2
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  build_runner: ">=1.12.2 <3.0.0"
  flutter_lints: ^2.0.1

flutter:
